[package]
org = "sameerag"
name = "clinical_note_summarizer_demo"
version = "0.1.0"

[[dependency]]
org = "wso2healthcare"
name = "health.ccdatojson"
version = "0.1.0"
repository="local"

[[dependency]]
org = "ballerinax"
name = "health.fhir.r4utils.ccdatofhir"
version = "3.0.1"
repository="local"